apiVersion: v1
kind: Secret
metadata:
  name: uaa-default-services
  namespace: fiori-mcp-test
type: Opaque
stringData:
  default-services.json: |
    {
      "uaa": {
        "clientid": "sb-inventory-management!t35119",
        "clientsecret": "66234e74-0efe-44d5-9831-f4736ed78fc9$t94zI7U2KY7uBD13D4XydAiPgSno9ziZeUDvQOTYd7A=",
        "url": "https://btpkymaenv-49u1ke1h.authentication.ap12.hana.ondemand.com",
        "uaadomain": "authentication.ap12.hana.ondemand.com",
        "xsappname": "inventory-management!t35119",
        "identityzone": "btpkymaenv-49u1ke1h",
        "identityzoneid": "84b53418-8804-4579-83e7-b5bb575970a8",
        "tenantid": "84b53418-8804-4579-83e7-b5bb575970a8",
        "tenantmode": "dedicated",
        "credential-type": "binding-secret",
        "verificationkey": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxieQ+1Agkp7SwIsZPGp1\nHpH0PREXRZARHqhKnajWot3qEXRDY4NsAeS3vocVT4R61G5PtNj7MecENKkGr9Ue\nNPNBtEXQjgw11mReJrMysqY8CnZ+kcSjGaHpkPfyVc8DfOfXVyMWiw7Qw5FWw+G8\n4PoOr03z0vZ4L11pjZ1rPHXbmvt1HF8EYtxJiiZ0e9GN/+1oB8nwalCSK8fDfqn/\nLYYLqoQ6DCktfn+wgN5dqqym7OTqzRtKNj0/x2WlDiVVHjbdZF43P7DHNUFg+LaB\n0ltqJeT+5BJyXt0nlyv2ZRADiEjuurb/F4ny4coU55wTrrxHFSRsdAany7za7P95\n2QIDAQAB\n-----END PUBLIC KEY-----",
        "sburl": "https://internal-xsuaa.authentication.ap12.hana.ondemand.com",
        "apiurl": "https://api.authentication.ap12.hana.ondemand.com"
      }
    }